version: 2

models:
  - name: customers
    description: One record per customer
    columns: 
      - name: customer_id
        description: id for clients
        tests: 
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: first_order_date
      - name: most_recent_order_date
      - name: number_of_orders
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              field: customer_id
              to: ref('stg_customers')
      - name: order_date
      - name: status 
